apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "another-test-file"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "secretFile"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "secret file credential from Kubernetes"
type: Opaque
stringData:
  filename: mySecret.txt
data:
# base64 encoded bytes
  data: SGVsbG8gV29ybGQh # Hello World!